// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School_Managment.DBcontext;

#nullable disable

namespace School_Managment.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    [Migration("20240328110341_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("School_Managment.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EMPName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("School_Managment.Model.Student", b =>
                {
                    b.Property<int?>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("student_id"), 1L, 1);

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("name1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("performance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("roll")
                        .HasColumnType("int");

                    b.HasKey("student_id");

                    b.ToTable("StudentLists");
                });
#pragma warning restore 612, 618
        }
    }
}
